### ISSUE TITLE
列表数据过多时，怎么出现滚动条？

### ISSUE THREAD

**Issue by hengchengfei** [lifution/FSPopoverView#13]

**Comment by lifution** [comment]
这个功能会在下个版本加上, 到时也会加上限制最多显示多少行. 目前你可以自己修改源码达到你想到的效果.
```objc
// 在 PopoverView 内部 UITableView 初始化的时候, 把这句代码注释即可.
_tableView.showsVerticalScrollIndicator = NO;
```

**Comment by hengchengfei** [comment]
加了，没有用，主要是限制显示多少行，这个功能比较重要。

**Comment by lifution** [comment]
不是加上这句代码, 是把这句代码注释掉, 这是隐藏滚动条的代码, 注释后应该就会在滑动的时候显示滚动条了. 限制行数的功能会在近期加上的. 😁

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
