### ISSUE TITLE
点击外部不会隐藏弹窗   之后测试了您的dome  也是不好不会隐藏  

### ISSUE THREAD

**Issue by xiaoxuanQi** [lifution/FSPopoverView#14]

**Comment by lifution** [comment]
有一个属性叫 `hideAfterTouchOutside` 是控制是否允许点击外部隐藏弹窗的，你看一下你的代码是否设置了这个属性为 `NO`，这个属性默认为 `YES` 的。

**Comment by xiaoxuanQi** [comment]
这个我知道  我测试了 我昨天尝试的把交互都开了  是不隐藏的   我测试那个点击的手势  只有在self上边起作用  全屏的覆盖view是不起作用的  我尝试改  但是没改好

**Comment by xiaoxuanQi** [comment]
这个  。。。。  有点尴尬  我的电脑 昨天 抽风了  好几个问题  今天都没有了
