### ISSUE TITLE
FSActionSheet 不能提issue 

### ISSUE THREAD

**Issue by csc-EricWu** [lifution/FSPopoverView#16]
![image](https://user-images.githubusercontent.com/13517061/57594311-eb3e6580-7571-11e9-8fc3-a0935a882f9f.png)
微信的这个subtitle 能实现吗？现在好多社区类产品都是抄袭微信的。
FSActionSheet 貌似只兼容了iPhone X 没有兼容iPhone XR  ,iPhone XS Max

**Comment by csc-EricWu** [comment]
![image](https://user-images.githubusercontent.com/13517061/57594357-322c5b00-7572-11e9-9b46-ecedf56e0251.png)

**Comment by lifution** [comment]
FSActionSheet 已不再维护，我准备写一个 FSActionSheetController 代替，到时候会加上 subTitle 的特性，预计是本周内能写好。😀

**Comment by csc-EricWu** [comment]
很棒，期待～！

**Comment by csc-EricWu** [comment]
大神，FSActionSheetController 开发好了么？我们有个功能模仿微信来做的，要求和微信一摸一样😅

**Comment by lifution** [comment]
这两周有点忙，耽搁了，估计是这周末能完成。

**Comment by csc-EricWu** [comment]
哈哈，期待～！

**Comment by csc-EricWu** [comment]
新的组件完成了吗？大神，😄
