### ISSUE TITLE
使用这个库之后导致 SVProgressHUD 无法显示

### ISSUE THREAD

**Issue by hw20101101** [lifution/FSPopoverView#18]
在 Test1ViewController 中弹出 PopoverView，
选中 PopoverView 的 item 之后 push 到 Test2ViewController （_Test2ViewController 的 viewDidLoad 中 调用了 [SVProgressHUD show];_ ）  
但是 SVProgressHUD 却无法显示。

**Comment by lifution** [comment]
这个库近期准备重构，到时候一并解决该问题，谢谢你的反馈。
