### ISSUE TITLE
Not getting selected Index from FSPopoverListTextItem

### ISSUE THREAD

**Issue by mohitordex** [lifution/FSPopoverView#21]
![Screenshot 2024-02-27 at 4 22 55 PM](https://github.com/lifution/FSPopoverView/assets/111515330/d507f6b6-9a88-434f-b282-2ec558e925e3)

Item.selectorHandler is giving item, but i need selected Index. As shown above image i am using stores which is a [String]. We are showing stores name in list and store name can be same so i was wondering if there's any way to get the selected Index from the selectedHandler Closure. 

I have tried to set the tag property but couldn't find any object on which i can set it.

Any help will be appreciated. Thank you!

**Comment by lifution** [comment]
Try the following:
```Swift
let items = stores.enumerated().map { (index, store) in
    let item = FSPopoverListTextItem()
    item.title = store
    item.selectedHandler = { item in
        guard let item = item as? FSPopoverListTextItem else {
            return
        }
        print("did select item at [\(index)]")
    }
    item.updateLayout()
    return item
}
```
