### ISSUE TITLE
Add SPM support

### ISSUE THREAD

**Issue by parmar-mehul** [lifution/FSPopoverView#22]
Hello @lifution ,

Can you please add SPM support? 
> XCode Version 15.3 (15E204a)
> iOS 17.4

![Screenshot 2024-03-07 at 3 02 10 PM](https://github.com/lifution/FSPopoverView/assets/98015131/7b3ad0e9-26b8-42d1-801e-7539a6db3c48)

**Comment by parmar-mehul** [comment]
#23 

Added support, Fixed issues, 
Waiting for approval from @lifution 

Thank you!

**Comment by lifution** [comment]
Done.
Thank you!
