### ISSUE TITLE
可以支持修改箭头的方向偏移量吗？

### ISSUE THREAD

**Issue by callmewenxi** [lifution/FSPopoverView#25]
可以支持修改箭头的方向偏移量吗？
现在好像是自动计算偏移的，但是有UI需求导致需要手动控制箭头居左还是居右

**Comment by lifution** [comment]
如果要手动控制箭头的方向，可以将 `autosetsArrowDirection` 设置为 `false`，然后通过 `arrowDirection` 来控制箭头的方向。

**Comment by callmewenxi** [comment]
> 如果要手动控制箭头的方向，可以将 `autosetsArrowDirection` 设置为 `false`，然后通过 `arrowDirection` 来控制箭头的方向。

这个我知道。
我的意思是，如果位置够的话，箭头是默认居中的，我想修改箭头，让它向左或者向右偏移
<img width="497" alt="image" src="https://github.com/user-attachments/assets/cd8622a0-cbcf-441c-8536-6020c9f2c4f1">

**Comment by lifution** [comment]
这种情况的话，你可以使用 `present(fromPoint xxx)` 这个方法来弹出 popover view，这样你就可以控制箭头指向的位置了。

**Comment by callmewenxi** [comment]
> 这种情况的话，你可以使用 `present(fromPoint xxx)` 这个方法来弹出 popover view，这样你就可以控制箭头指向的位置了。

感谢，用这个方法实现了，主要要控制displayIn，让它算位置的时候，不按全屏幕计算，箭头就会有一定的偏移
`
    open func present(fromView view: UIView,
                      displayIn specifiedView: UIView? = nil,
                      animated: Bool = true,
                      completion: (() -> Void)? = nil) {
        p_present(from: view.frame,
                  in: view.superview,
                  displayIn: specifiedView,
                  animated: animated,
                  completion: completion)
    }
`
