### ISSUE TITLE
iOS11 设备上显示异常

### ISSUE THREAD

**Issue by andy123234** [lifution/FSPopoverView#5]
![simulator screen shot - iphone 8 - 2017-09-25 at 11 23 50](https://user-images.githubusercontent.com/15189830/30791276-0bb273aa-a1e4-11e7-84c8-1cc476c69173.png)
底部会多一块空白

**Comment by andy123234** [comment]
已经解决了,在PopoverView.m 115行加上

**Comment by andy123234** [comment]
已经解决了,在PopoverView.m 115行加上
_tableView.estimatedRowHeight = 0;
_tableView.estimatedSectionHeaderHeight = 0;
_tableView.estimatedSectionFooterHeight = 0;

**Comment by lifution** [comment]
@andy123234 你应该是使用cocoapods引入的, 适配iOS11的版本我忘记更新到cocoapods了. 😂
