### ISSUE TITLE
在iPhoneX上运行，导航栏左按钮那里布局显示尴尬😅

### ISSUE THREAD

**Issue by TML007** [lifution/FSPopoverView#6]

**Comment by lifution** [comment]
导航栏左按钮是使用指定的 CGPoint 来弹出的, 这个 point 需要开发者指定, 所以在使用的时候如果需要使用 point 来弹出菜单的话, 建议根据是否是 iPhone X 来改变一下这个 point 的 y 轴坐标. 🙂
