### ISSUE TITLE
悬浮按钮弹出问题

### ISSUE THREAD

**Issue by weitaishan** [lifution/FSPopoverView#7]
我本身点击的时候，就是一个悬浮按钮，这时候弹出的视图会有问题，是因为我之前的window视图影响吗？

**Comment by lifution** [comment]
PopoverView是会被 add 到 keyWindow 上的, 你是否是修改过 keyWindow 呢 ?

**Comment by weitaishan** [comment]
看了您的源码，我解决了这个问题，由于您是获取的当前的window，导致我添加的window的层级不对，我就自己创建了一个window，与我的window视图同级
_keyWindow = [[UIWindow alloc] initWithFrame:SCREEN_FRAME];
    _keyWindow.windowLevel = UIWindowLevelAlert + 1;
    [_keyWindow makeKeyAndVisible];
解决了问题，非常感谢

**Comment by lifution** [comment]
那就好 😁
